name: 'Convert markdown'
description: 'Convert markdown to Confluence markup'
inputs:
  markdown:
    description: 'Markdown to convert to Confluence markup'
    required: true
outputs:
  confluence_markup:
    description: 'Content converted to Confluence markup'
runs:
  using: 'node12'
  main: 'dist/index.js'
